services:
  app:
    image: ngntu10/caffeetrio:latest
    container_name: ngntu10-spring-app
#    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://nt118p22-cafetrio.i.aivencloud.com:25794/defaultdb
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_tqpyXsGYH2HDhHtkwod
    ports:
      - "8080:8080"
    networks:
      - ngntu10-network
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ngntu10-mailhog
    restart: always
    ports:
      - "8025:8025"
      - "587:587"
    networks:
      - ngntu10-network
networks:
  ngntu10-network:
    name: ngntu10-network
    driver: bridge
